### PR TITLE
[IPU] update docs and custom ops demo

### PR DESCRIPTION
**Pull request by yaozhixin**
support paddle inference x IPU with custom ops

### CODE REVIEW

**Review by qili93 — APPROVED** [review]
LGTM

**Review by leiqing1 — APPROVED** [review]

**Comment by gglin001** [comment]
CI `Test-docs-CI` 似乎总是会失败, 看log与pr 内容无关

**Comment by gglin001** [comment]
这个 pr 将会close, 修改迁移到 
- https://github.com/PaddlePaddle/Paddle-Inference-Demo/pull/366

**Comment by gglin001** [comment]
这个 pr 将会close, 修改迁移到 
- https://github.com/PaddlePaddle/Paddle-Inference-Demo/pull/366

**Pull request closed without merging**
